function(bats_discover_tests SCRIPT_FILES)
    message("Passed script files is ${SCRIPT_FILES}")
    foreach (SCRIPT_FILE IN LISTS SCRIPT_FILES)
        if(NOT "${SCRIPT_FILE}" STREQUAL "")
            message("script path is ... ${SCRIPT_FILE}")
            file(STRINGS ${SCRIPT_FILE} TEST_LINES REGEX ".*@test.*")
            message("lines are ... ${TEST_LINES}")
            foreach (TEST_LINE IN LISTS TEST_LINES)

                message("line is ${TEST_LINE}")
                string(FIND ${TEST_LINE} "\"" firstQuoteIndex)
                string(FIND ${TEST_LINE} "\"" secondQuoteIndex REVERSE)
                message("f is ${firstQuoteIndex}")
                MATH(EXPR firstQuoteIndex "${firstQuoteIndex}+1")
                MATH(EXPR nameLength "${secondQuoteIndex}-${firstQuoteIndex}")
                string(SUBSTRING ${TEST_LINE} ${firstQuoteIndex} ${nameLength} TEST_NAME)
                add_test(NAME ${TEST_NAME}
                        COMMAND ${SCRIPT_FILE} -f "${TEST_NAME}")
            endforeach()
        endif()
    endforeach()
endfunction()