function(bats_discover_tests SCRIPT_FILES)
    foreach (SCRIPT_FILE IN LISTS SCRIPT_FILES)
        if(NOT "${SCRIPT_FILE}" STREQUAL "")
            file(STRINGS ${SCRIPT_FILE} TEST_LINES REGEX ".*@test.*")
            foreach (TEST_LINE IN LISTS TEST_LINES)
                string(FIND ${TEST_LINE} "\"" firstQuoteIndex)
                string(FIND ${TEST_LINE} "\"" secondQuoteIndex REVERSE)
                MATH(EXPR firstQuoteIndex "${firstQuoteIndex}+1")
                MATH(EXPR nameLength "${secondQuoteIndex}-${firstQuoteIndex}")
                string(SUBSTRING ${TEST_LINE} ${firstQuoteIndex} ${nameLength} TEST_NAME)
                add_test(NAME ${TEST_NAME}
                        COMMAND ${bats_SOURCE_DIR}/bin/bats ${SCRIPT_FILE} -f "${TEST_NAME}")
            endforeach()
        endif()
    endforeach()
endfunction()